### PR TITLE
Item spawn rate

### PR DESCRIPTION
**Pull request by jaybruce1998**
The spawn rate can now be modified, and the .gitignore file no longer exists.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts to this pull request.

**Comment by jaybruce1998** [comment]
So there is no DocumentBuilderFactory... hmm...

**Comment by mgb2403** [comment]
Dependent on #26

**Comment by Bhargavicm** [comment]
#26 is now merged. Please resolve conflicts on this pull request

**Comment by Bhargavicm** [comment]
#26 is now merged. Please resolve conflicts on this pull request. If this is not a valid pull request please close this one.

**Comment by Bhargavicm** [comment]
I see the .gitignore being deleted, this merge would delete the file from the server. Please exclude that from your pull request if you do not want the file to be merged.

**Comment by jaybruce1998** [comment]
Wait I'm confused... I didn't add, commit or push .gitignore this time? So it shouldn't delete anything when you merge...

**Comment by Bhargavicm** [comment]
Your pull request has .gitignore file. Could you just remove that from your pull request?

**Comment by jaybruce1998** [comment]
Let me know if it's still not good

**Comment by Bhargavicm** [comment]
Looks good. I will go ahead and merge.

**Pull request merged**
