### PR TITLE
Quest rewards

### PR DESCRIPTION
**Pull request by cmccread**
Added a command to print out Quest information the the player.
Added Quest rewards.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by cmccread** [comment]
fixed merge conflicts several days ago (I believe the very next day after seeing I was asked to fix merge conflcits), still seeing:
"This branch has no conflicts with the base branch"
Am I missing something...?

**Comment by gildir** [comment]
When merged in I'm getting the following on build:

```
Player.java:46: error: class, interface, or enum expected
	public ArrayList<Quest> getQuestBook()
	       ^
Player.java:49: error: class, interface, or enum expected
	}
	^
Player.java:51: error: class, interface, or enum expected
  public Money giveMoney(Player giver,Player receiver,double value){
         ^
Player.java:53: error: class, interface, or enum expected
    replyWriter.println("You are giving away "+ String.format("%1$,.2f", value)); 
    ^
Player.java:55: error: class, interface, or enum expected
    if(this.money.sum() <= 0){
    ^
Player.java:57: error: class, interface, or enum expected
      return moneyToGive;
      ^
Player.java:58: error: class, interface, or enum expected
    } 
    ^
Player.java:62: error: class, interface, or enum expected
    int[] unitsGiven = new int[5];
    ^
Player.java:63: error: class, interface, or enum expected
    int[] numUnits = new int[]{this.money.numFives, this.money.numOnes, this.money.numQuarters, this.money.numDimes, this.money.numPennies};
    ^
Player.java:64: error: class, interface, or enum expected
    double[] unitVals = new double[]{5, 1, 0.25, 0.10, 0.01};
    ^
Player.java:65: error: class, interface, or enum expected
    int index = 0;
    ^
Player.java:67: error: class, interface, or enum expected
    while(index < 5){
    ^
Player.java:68: error: class, interface, or enum expected
      for (int i = 1; i <= numUnits[index]; i++){
                      ^
Player.java:68: error: class, interface, or enum expected
      for (int i = 1; i <= numUnits[index]; i++){
                                            ^
Player.java:71: error: class, interface, or enum expected
        }
        ^
Player.java:73: error: class, interface, or enum expected
      }
      ^
Player.java:77: error: class, interface, or enum expected
      }
      ^
Player.java:79: error: class, interface, or enum expected
    }
    ^
Player.java:83: error: class, interface, or enum expected
      return moneyToGive;
      ^
Player.java:84: error: class, interface, or enum expected
    }
    ^
Player.java:88: error: class, interface, or enum expected
      moneyToGive.numOnes = unitsGiven[1];
      ^
Player.java:89: error: class, interface, or enum expected
      moneyToGive.numQuarters = unitsGiven[2];
      ^
Player.java:90: error: class, interface, or enum expected
      moneyToGive.numDimes = unitsGiven[3];
      ^
Player.java:91: error: class, interface, or enum expected
      moneyToGive.numPennies = unitsGiven[4];
      ^
Player.java:92: error: class, interface, or enum expected
      receiver.addMoney(moneyToGive); 
      ^
Player.java:93: error: class, interface, or enum expected
      removeMoney(moneyToGive);   
      ^
Player.java:94: error: class, interface, or enum expected
      receiver.getReplyWriter().println("You received " + String.format("%1$,.2f", value) + " dollars!"); 
      ^
Player.java:95: error: class, interface, or enum expected
      return moneyToGive;
      ^
Player.java:96: error: class, interface, or enum expected
    }
    ^
Player.java:99: error: class, interface, or enum expected
  public String viewInventory() {
         ^
Player.java:101: error: class, interface, or enum expected
    if(this.currentInventory.isEmpty() == true) {
    ^
Player.java:103: error: class, interface, or enum expected
    }
    ^
Player.java:107: error: class, interface, or enum expected
      }
      ^
Player.java:109: error: class, interface, or enum expected
    }
    ^
Player.java:111: error: class, interface, or enum expected
    return result;
    ^
Player.java:112: error: class, interface, or enum expected
  }
  ^
Player.java:115: error: class, interface, or enum expected
  public String toString() {
         ^
Player.java:117: error: class, interface, or enum expected
  }
  ^
Player.java:120: error: class, interface, or enum expected
  public void ignorePlayer(String name) {
         ^
Player.java:122: error: class, interface, or enum expected
  }
  ^
Player.java:124: error: class, interface, or enum expected
  public void addIgnoredBy( String name) {
         ^
Player.java:126: error: class, interface, or enum expected
  }
  ^
Player.java:128: error: class, interface, or enum expected
  public boolean searchIgnoredBy(String name) {
         ^
Player.java:130: error: class, interface, or enum expected
    for( int x = 0; x < listSize; x++){
    ^
Player.java:130: error: class, interface, or enum expected
    for( int x = 0; x < listSize; x++){
                    ^
Player.java:130: error: class, interface, or enum expected
    for( int x = 0; x < listSize; x++){
                                  ^
Player.java:133: error: class, interface, or enum expected
        this.name = name;
        ^
Player.java:134: error: class, interface, or enum expected
        this.currentInventory = new LinkedList<>();
        ^
Player.java:135: error: class, interface, or enum expected
        this.currentSpirits = new LinkedList<>();
        ^
Player.java:136: error: class, interface, or enum expected
        try {
        ^
Player.java:139: error: class, interface, or enum expected
            questBook.get(0).printQuest();
            ^
Player.java:140: error: class, interface, or enum expected
        } catch (FileNotFoundException fnfe) {
        ^
Player.java:142: error: class, interface, or enum expected
        }
        ^
Player.java:145: error: class, interface, or enum expected
        this.ignoreList = new ArrayList<String>();
        ^
Player.java:146: error: class, interface, or enum expected
        this.ignoredByList = new ArrayList<String>();
        ^
Player.java:148: error: class, interface, or enum expected
    }
    ^
Player.java:150: error: class, interface, or enum expected
    public void turnLeft() {
           ^
Player.java:155: error: class, interface, or enum expected
                    break;
                    ^
Player.java:156: error: class, interface, or enum expected
                case "South":
                ^
Player.java:158: error: class, interface, or enum expected
                    break;
                    ^
Player.java:159: error: class, interface, or enum expected
                case "East":
                ^
Player.java:161: error: class, interface, or enum expected
                    break;
                    ^
Player.java:162: error: class, interface, or enum expected
                case "West":
                ^
Player.java:164: error: class, interface, or enum expected
                    break;
                    ^
Player.java:165: error: class, interface, or enum expected
            }
            ^
Player.java:169: error: class, interface, or enum expected
    public void turnRight() {
           ^
Player.java:174: error: class, interface, or enum expected
                    break;
                    ^
Player.java:175: error: class, interface, or enum expected
                case "South":
                ^
Player.java:177: error: class, interface, or enum expected
                    break;
                    ^
Player.java:178: error: class, interface, or enum expected
                case "East":
                ^
Player.java:180: error: class, interface, or enum expected
                    break;
                    ^
Player.java:181: error: class, interface, or enum expected
                case "West":
                ^
Player.java:183: error: class, interface, or enum expected
                    break;
                    ^
Player.java:184: error: class, interface, or enum expected
            }
            ^
Player.java:188: error: class, interface, or enum expected
    public String getName() {
           ^
Player.java:190: error: class, interface, or enum expected
    }
    ^
Player.java:193: error: class, interface, or enum expected
    public String getNameWithTitle(){
           ^
Player.java:197: error: class, interface, or enum expected
            }
            ^
Player.java:200: error: class, interface, or enum expected
            }
            ^
Player.java:204: error: class, interface, or enum expected
    public void setName(String name) {
           ^
Player.java:207: error: class, interface, or enum expected
        }
        ^
Player.java:210: error: class, interface, or enum expected
    public void setTitle(String title){
           ^
Player.java:213: error: class, interface, or enum expected
        }
        ^
Player.java:216: error: class, interface, or enum expected
    public void setIsDrunk(Boolean trueOrFalse){
           ^
Player.java:219: error: class, interface, or enum expected
        }
        ^
Player.java:222: error: class, interface, or enum expected
    public Boolean getIsDrunk(){
           ^
Player.java:224: error: class, interface, or enum expected
    }
    ^
Player.java:226: error: class, interface, or enum expected
    public void setLastWhisperName(String name) {
           ^
Player.java:229: error: class, interface, or enum expected
        }
        ^
Player.java:232: error: class, interface, or enum expected
    public String getLastWhisperName() {
           ^
Player.java:234: error: class, interface, or enum expected
    }
    ^
Player.java:236: error: class, interface, or enum expected
    public LinkedList<Item> getCurrentInventory() {
           ^
Player.java:238: error: class, interface, or enum expected
    }
    ^
Player.java:240: error: class, interface, or enum expected
    public void setCurrentInventory(LinkedList<Item> currentInventory) {
           ^
Player.java:243: error: class, interface, or enum expected
        }
        ^
Player.java:246: error: class, interface, or enum expected
    public void addObjectToInventory(Item object) {
           ^
Player.java:249: error: class, interface, or enum expected
        }
        ^
Player.java:252: error: class, interface, or enum expected
    public Item removeObjectFomInventory(String object) {
           ^
Player.java:257: error: class, interface, or enum expected
                    return obj;
                    ^
Player.java:258: error: class, interface, or enum expected
                }
                ^
100 errors
```

**Comment by gildir** [comment]
Please reopen or create a new pull request where this has been resolved.

**Pull request merged**
