### PR TITLE
301 Cardinal Movement

### PR DESCRIPTION
**Pull request by Platem**
Change the movement system so instead of having to turn left/right, you can say directly a cardinal direction (North, south, east, west) and move there.

This branch includes merge from feature 302 (as both of them change the movement system and need to be compliant with each other).

It also includes merge from feature 304 (as we changed how the commands system work, and want to make them compliant with each other).

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Looks good.

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by Platem** [comment]
Done.

**Comment by Bhargavicm** [comment]
Please resolve conflicts on this pull request.

**Comment by Platem** [comment]
Done. Again.

**Pull request merged**
