### PR TITLE
Added PvP Readme and Images to root

### PR DESCRIPTION
**Pull request by ryan1246**
Learned how to do it correctly.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
I will do all the sprint 3 merges after I finish all the teams merge with sprint 1 and sprint 2.

**Comment by ryan1246** [comment]
Switched.

**Comment by Bhargavicm** [comment]
This has 57 files modified. Please clarify which items do these belong to?

**Comment by ryan1246** [comment]
My bad. I pulled dev and added it to that. You then asked me to switch it to Master. That's what happened. Just to be clear the readme needs to be to the master branch? Before I go and redo this, I just want to make sure.

**Pull request closed without merging**
