### PR TITLE
314 Code Review

### PR DESCRIPTION
**Pull request by kevinrpb**
Applied fixes suggested by the Team 1's review. Basically code commenting and javadocs.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by gildir** [comment]
Still not updated.

**Comment by kevinrpb** [comment]
Had missed this. Should be ok now.

**Comment by gildir** [comment]
You appear to have removed the menu in your update (probably removing the line createCommands() ?).

**Comment by gildir** [comment]
Please reopen or create a new pull request where this has been resolved.

**Comment by kevinrpb** [comment]
Yes, I saw the problem. My branch was not staging the file for some reason. I opened a new PR.

Thanks.

**Pull request merged**
