### PR TITLE
202 203 uname pass login

### PR DESCRIPTION
**Pull request by htanvee**
We received permission from Prof. Russell to combine these two features because they build directly off each other

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts to this pull request.

**Comment by htanvee** [comment]
I committed the resolved conflicts on my IDE but it won't let me push because it says I do not have access to the repo... Are you still able to see my changes?

**Comment by htanvee** [comment]
How do I see where the actual problems are?

**Comment by Bhargavicm** [comment]
You should be able to see conflicts in two files for this pull request, src/GameClient.java
src/GameObject.java. In your pull request, all the way down you can see if there are conflicts and which files too. 

Please ensure you are looking into the dev and not master to resolve your conflicts.

**Comment by htanvee** [comment]
My dev does not show any changes being made in the main repo

**Comment by htanvee** [comment]
Reopened.

**Pull request merged**
