### PR TITLE
409 censor words read from file

### PR DESCRIPTION
**Pull request by amarti74**
Hello,
I'm attempting to merge feature 409. I'm in team 5, section 2.

Thanks,
Amilcar

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by amarti74** [comment]
Hello,
Conflicts have been resolved.

-Amilcar

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by amarti74** [comment]
conflicts fixed.

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by amarti74** [comment]
conflicts fixed.

**Pull request merged**
