### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mgb2403**
This pull request contains the changes for stories 101, 102, 104, and 105. Only 1 pull request because all the changes are too interconnected for multiple pulls.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please undo your changes to runClientLocal.bat, runServer.bat, runServer.sh. These features should not require any changes.

**Comment by mgb2403** [comment]
The changes to runServer.sh and bat are necessary to allow the server to accept a comment line argument specifying the rooms file to use.

**Comment by Bhargavicm** [comment]
I get that. Sounds good!

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by mgb2403** [comment]
Whoops, didn't mean to hit the commit merge button without having you verify I did it right. My bad.

**Comment by Bhargavicm** [comment]
You still have conflicts. Please coordinate and merge files.

**Pull request merged**
