### PR TITLE
413_Time stamps

### PR DESCRIPTION
**Pull request by jahenkor**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve merge conflicts for this pull request

**Comment by jahenkor** [comment]
Resolved

**Comment by Bhargavicm** [comment]
You may want to get rid of the chat_log.txt as its a log file and will be created per server/user.

**Comment by jahenkor** [comment]
Resolved

**Comment by Bhargavicm** [comment]
Merged!!!

**Pull request merged**
