### PR TITLE
201 login/logout log

### PR DESCRIPTION
**Pull request by htanvee**
Updated pull request

### CODE REVIEW

**Comment by htanvee** [comment]
Hi -- This has the updated feature branch. All conflicts resolved and it works!

**Comment by Bhargavicm** [comment]
Merging this item blew off the menu items. Please run the code that is currently in dev and then merge your changes and send a pull request.

**Comment by htanvee** [comment]
What do you mean blew off menu items? It worked when I tested with latest code

**Comment by htanvee** [comment]
I am looking at the code and it seems it was doing that before my merge

**Comment by htanvee** [comment]
#103

**Pull request merged**
