### PR TITLE
Team 8 Readme

### PR DESCRIPTION
**Pull request by ryan1246**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
I don't understand your file changes. What items are included here? It says 50 files changed, if it is related to the readme for sprint 3, I don't think you all these files are related to your changes. Please include only files related to Sprint 1 and Sprint 2 first. Sprint 3 can have a separate pull request.

**Comment by ryan1246** [comment]
I have been trying to make it so that there arent any merge conflicts so I just downloaded the latest version of dev from the main repo and added my Readme to that. I dont understand why it keeps saying so many files changed

**Comment by ryan1246** [comment]
I am completely confused about how to proceed. By downloading all files from the main dev branch I shouldn't have any problems correct? I took all those files and replaced everything on my branch, then I added the readme and images for this sprint. Am I missing something important here?

**Comment by ryan1246** [comment]
Oh I think I understand, the 50 files changed are probably the result of me overwriting my branch with the files from the main dev. Those changes it is yelling about are from converting my repository's code to match the current main dev branch.

**Comment by ryan1246** [comment]
How do I get it to not say this?

**Comment by Bhargavicm** [comment]
You may want to pull the Dev to reflect your code base in your local. After which I would say make changes to your readme related pull request. If this is related to Sprint 3 then I will not be merging until I have all the items from all the teams for both sprints merged.

**Comment by ryan1246** [comment]
ok will do

**Pull request closed without merging**
