### PR TITLE
206 delete character option

### PR DESCRIPTION
**Pull request by htanvee**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts to this pull request.

**Comment by htanvee** [comment]
I committed the resolved conflicts on my IDE but it won't let me push because it says I do not have access to the repo... Are you still able to see my changes?

**Comment by Bhargavicm** [comment]
Nope. It still says there are merge conflicts. I would suggest you look into what's latest and try to resolve your conflicts.

**Comment by htanvee** [comment]
Yeah but where do I see the changes? What do I checkout to in my IDE? What commands do I use to see the changes being made? I am completely lost for fixing these offline. I don't understand how I would get the changes in the main repo and then fix the conflicts in this branch

**Comment by htanvee** [comment]
Reopened.

**Pull request merged**
