### PR TITLE
701, 710, 705, 706, 707, 717, 718, 719, 716, 721

### PR DESCRIPTION
**Pull request by KevinRickard**

### CODE REVIEW

**Comment by ryan-hoang** [comment]
Hey, this is the leader of team 8, you guys reached out to us after class, I didn't have your email so I made a Piazza post. In the post I attached a modified Ghoul.java that I got from your 716_fight_ghoul branch. This should prevent any conflicts between our two user stories. Take a look at the post and email me if there's still problems.

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request. Also please reason out why all your features are merged in a single pull request.

**Comment by KevinRickard** [comment]
@ryan1246 Awesome, I'll talk to Thomas and we'll get that sorted. Thanks for doing that.

@Bhargavicm Our stories are all interconnected (relating to the monsters), building off of the previous stories and sometimes relating to stories that are in process by other members of the team. So we just work off of our own dev branch where our stories are already merged together. I've been doing one pull request from our dev for each sprint but we didn't last week's stories approved approved until today so now we have double the stories to merge.

**Comment by Bhargavicm** [comment]
Sounds good. Please resolve the conflicts and I will have them merged.

**Comment by ryan-hoang** [comment]
We have been merged, you can go ahead and merge with the modified Ghoul.java. @KevinRickard @TWash8

**Comment by KevinRickard** [comment]
Ready to merge

**Pull request merged**
