### PR TITLE
201 login/logout log

### PR DESCRIPTION
**Pull request by htanvee**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts to this pull request.

**Comment by htanvee** [comment]
I have a question. How do I know which commits I have to fix?
It said I cant edit on web and had to do it on an editor and I did that and it shows me everyones changes

**Comment by htanvee** [comment]
I committed the resolved conflicts on my IDE but it won't let me push because it says I do not have access to the repo... Are you still able to see my changes?

**Comment by htanvee** [comment]
I am confused... How do I still resolve these conflicting files?
If I open the file on my feature branch it is fine with the changes.. Please advise

**Comment by htanvee** [comment]
Reopened.

**Comment by Bhargavicm** [comment]
Please resolve the conflicts on this pull request.

**Comment by Bhargavicm** [comment]
I see this error when I build the server. Please fix and resend the code.

GameObject.java:138: error: illegal start of type
     * @throws RemoteException
     ^
GameObject.java:138: error: <identifier> expected
     * @throws RemoteException
        ^
GameObject.java:138: error: = expected
     * @throws RemoteException
               ^
GameObject.java:138: error: ';' expected
     * @throws RemoteException
                              ^
GameObject.java:139: error: illegal start of type
     */
      ^
GameObject.java:139: error: <identifier> expected
     */
       ^
GameObject.java:140: error: = expected
    @Override
     ^
GameObject.java:140: error: ';' expected
    @Override
             ^
8 errors

**Comment by htanvee** [comment]
I apologize about that. I fixed it. It seems there was a comment opening line (/**) missing when it was merged.

**Comment by Bhargavicm** [comment]
You will need to make a new pull request with your changes for me to merge.

**Comment by htanvee** [comment]
Sorry.. Pull request @86

**Comment by Bhargavicm** [comment]
I do not see any new pull request made to dev. Please make a new pull request to dev.

**Comment by htanvee** [comment]
https://github.com/gildir/CS321-2018F-002/pull/86

**Comment by htanvee** [comment]
It is showing up on mine as open.. It is request #86

**Comment by Bhargavicm** [comment]
Your login and logout had 7 files changed. This pull request contains only one file. Which item is this file related to? Please include all the files and also the task number to which it belongs to. 

Associate all the files for feature 201 in this pull request.

**Comment by htanvee** [comment]
I renamed it.. I do not understand why it is only doing one file. I am doing the pull request the same way I normally do.

**Pull request merged**
