### PR TITLE
Dev Team 5-002

### PR DESCRIPTION
**Pull request by shayhoss**
Stories:

401,402.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please undo your changes to .gitignore, LICENSE (specifically spacing changes), runServer.sh as they are not related to the features.

I see you have a combined two features in a single pull request. Please justify why it was combined.

**Comment by shayhoss** [comment]
The justification for merge: After merging the features, I(team leader) had to fix a bug related to a specific task. I fixed the bug in the dev branch(which I monitor), so our feature branch had a bug at the time.

runServer.sh: do Linux users have to fix the semicolon bug everytime they want to run their code? Is there a way that we can keep that fixed?

.gitignore: I'd like to negotiate on this one too. It is just a folder and a file to be ignored for my IDE to run. It will add to the efficiency of our team if we can keep that up.

**Comment by kornonfire** [comment]
To help make sure this gets seen, @Bhargavicm are these justifications satisfactory for the pull request? Please let us know as soon as possible so we can make sure our changes get pulled in case they are needed by another team.

**Comment by shayhoss** [comment]
Sprint 2 files added so, for demo purposes I need to close this pull request.

**Pull request closed without merging**
