### PR TITLE
406 ignored responsev2

### PR DESCRIPTION
**Pull request by jahenkor**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve merge conflicts for this pull request

**Comment by jahenkor** [comment]
Resolved conflicts

**Comment by jahenkor** [comment]
Resolved

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by jahenkor** [comment]
Resolved

**Comment by Bhargavicm** [comment]
I don't see any changes in the below files except the spaces. You may want to exclude that from your pull request ( Do not delete but exclude)
commands.csv
GameObjectInterface.java
GameObject.java
GameCoreInterface.java
CommandRunner.java

**Comment by jahenkor** [comment]
Resolved

**Pull request merged**
