### PR TITLE
820

### PR DESCRIPTION
**Pull request by ryan-hoang**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by ryan-hoang** [comment]
Resolved

**Comment by Bhargavicm** [comment]
Please resolve merge conflicts for this pull request.

**Comment by ryan-hoang** [comment]
resolved as of 9:29 am

**Comment by Bhargavicm** [comment]
GameCore.java has ScrubMessage which is part of 409. You might have accidentally removed while merging. Please replace the code as it was if that was not intended to remove.

**Comment by ryan-hoang** [comment]
I will fix that at once.

**Comment by ryan-hoang** [comment]
It should be back now. @Bhargavicm

**Comment by Bhargavicm** [comment]
You may want to fix the  ArrayList<String> censorList parameter being sent in some of the methods in GameCore.java. Please test your changes once you resolve conflicts in your local and then make an updated pull request.

**Comment by ryan-hoang** [comment]
These are not our methods. I am not sure how this happened; however, I have replaced these methods with the versions from the main repo. I have verified that they compile.
@Bhargavicm

**Comment by Bhargavicm** [comment]
You may want to take the latest copy that is in Dev now and then resolve the conflicts with your feature branch. Then make a pull request, by doing this you won't remove other team's code accidentally.

**Comment by ryan-hoang** [comment]
conflicts resolved

**Comment by Bhargavicm** [comment]
Reverting this change. Below is the error on server run.

java.io.FileNotFoundException: ./RPSdemoitems.csv (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.util.Scanner.<init>(Scanner.java:611)
        at ItemParser.parse(ItemParser.java:21)
        at GameCore$2.run(GameCore.java:137)
        at java.lang.Thread.run(Thread.java:748)
[RUN] Game Server is now running and accepting connections.
Exception in thread "Thread-3" java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at GameCore$2.run(GameCore.java:142)
        at java.lang.Thread.run(Thread.java:748)

**Pull request merged**
