### PR TITLE
303 Pickup all items at once

### PR DESCRIPTION
**Pull request by Platem**
When using the **PICKUP**, add the keyword `all` to pick all the items in the room.

### CODE REVIEW

**Comment by Bhargavicm** [comment]
Looks good.

**Comment by Bhargavicm** [comment]
Please resolve conflicts for this pull request.

**Comment by Platem** [comment]
Done.

**Comment by Platem** [comment]
Done. Again. But...
This branch solved the conflict of including the new Item class before. Now that was reverted. Those 'Item' references are included in several places, including others' branches. The game is not compiling right now.

**Pull request merged**
