### PR TITLE
Accounts and Login (Group 1) Readme

### PR DESCRIPTION
**Pull request by htanvee**

### CODE REVIEW

**Comment by Bhargavicm** [comment]
You will need to remove your changes from README.md file.

**Comment by htanvee** [comment]
Resolved

**Comment by htanvee** [comment]
I originally had replaced it with the accounts.md file

**Comment by Bhargavicm** [comment]
I can still see that attached to your pull request You may want to delete it.

**Comment by htanvee** [comment]
Originally it was not there. I created it after you said I needed to remove my changes. But I will delete it.

**Comment by Bhargavicm** [comment]
I meant to exclude the file from your pull request but looks like you have deleted. Once I merge these changes it will delete the actual file from the Master branch. Consider rebase from the master and just have your changes applied and make a pull request.

**Comment by htanvee** [comment]
#114

**Pull request closed without merging**
